steps:
  - task: DownloadPipelineArtifact@2

  - task: AzureRmWebAppDeployment@4
    displayName: 'Azure App Service Deploy'
    inputs:
      appType: webApp
      ConnectedServiceName: $(azureSubscriptionName)
      WebAppName: '$(WebAppName)-$(Environment.Name)'
      package: $(Pipeline.Workspace)/app/*.zip
